In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv(r"C:\Users\Lenovo\Desktop\Python\Datasets\Moneypox.csv")

In [4]:
data

Patient_ID     Systemic Illness  Rectal Pain  Sore Throat  \
0             P0                 None        False         True   
1             P1                Fever         True        False   
2             P2                Fever        False         True   
3             P3                 None         True        False   
4             P4  Swollen Lymph Nodes         True         True   
...          ...                  ...          ...          ...   
24995     P24995                 None         True         True   
24996     P24996                Fever        False         True   
24997     P24997                 None         True         True   
24998     P24998  Swollen Lymph Nodes        False         True   
24999     P24999  Swollen Lymph Nodes        False        False   

       Penile Oedema  Oral Lesions  Solitary Lesion  Swollen Tonsils  \
0               True          True            False             True   
1               True          True            False            False   
2               True         False            False            False   
3              False         False             True             True   
4               True         False            False             True   
...              ...           ...              ...              ...   
24995          False          True             True            False   
24996           True         False             True             True   
24997          False         False             True             True   
24998          False          True             True             True   
24999           True         False            False             True   

       HIV Infection  Sexually Transmitted Infection MonkeyPox  
0              False                           False  Negative  
1               True                           False  Positive  
2               True                           False  Positive  
3               True                           False  Positive  
4               True                           False  Positive  
...              ...                             ...       ...  
24995          False                            True  Positive  
24996           True                            True  Positive  
24997          False                           False  Positive  
24998          False                           False  Negative  
24999           True                           False  Positive  

[25000 rows x 11 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Patient_ID                      25000 non-null  object
 1   Systemic Illness                25000 non-null  object
 2   Rectal Pain                     25000 non-null  bool  
 3   Sore Throat                     25000 non-null  bool  
 4   Penile Oedema                   25000 non-null  bool  
 5   Oral Lesions                    25000 non-null  bool  
 6   Solitary Lesion                 25000 non-null  bool  
 7   Swollen Tonsils                 25000 non-null  bool  
 8   HIV Infection                   25000 non-null  bool  
 9   Sexually Transmitted Infection  25000 non-null  bool  
 10  MonkeyPox                       25000 non-null  object
dtypes: bool(8), object(3)
memory usage: 488.3+ KB


In [6]:
data.describe()

Patient_ID Systemic Illness Rectal Pain Sore Throat Penile Oedema  \
count       25000            25000       25000       25000         25000   
unique      25000                4           2           2             2   
top            P0            Fever       False        True          True   
freq            1             6382       12655       12554         12612   

       Oral Lesions Solitary Lesion Swollen Tonsils HIV Infection  \
count         25000           25000           25000         25000   
unique            2               2               2             2   
top           False            True            True          True   
freq          12514           12527           12533         12584   

       Sexually Transmitted Infection MonkeyPox  
count                           25000     25000  
unique                              2         2  
top                             False  Positive  
freq                            12554     15909

In [7]:
data.isnull().sum()

Patient_ID                        0
Systemic Illness                  0
Rectal Pain                       0
Sore Throat                       0
Penile Oedema                     0
Oral Lesions                      0
Solitary Lesion                   0
Swollen Tonsils                   0
HIV Infection                     0
Sexually Transmitted Infection    0
MonkeyPox                         0
dtype: int64

In [8]:
data["MonkeyPox"].value_counts()

Positive    15909
Negative     9091
Name: MonkeyPox, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()

In [10]:
data["Systemic Illness"]=l.fit_transform(data["Systemic Illness"])
data["Rectal Pain"]=l.fit_transform(data["Rectal Pain"])
data["Sore Throat"]=l.fit_transform(data["Sore Throat"])
data["Penile Oedema"]=l.fit_transform(data["Penile Oedema"])
data["Oral Lesions"]=l.fit_transform(data["Oral Lesions"])
data["Solitary Lesion"]=l.fit_transform(data["Solitary Lesion"])
data["Swollen Tonsils"]=l.fit_transform(data["Swollen Tonsils"])
data["HIV Infection"]=l.fit_transform(data["HIV Infection"])
data["Sexually Transmitted Infection"]=l.fit_transform(data["Sexually Transmitted Infection"])
data["MonkeyPox"]=l.fit_transform(data["MonkeyPox"])

In [11]:
data

Patient_ID  Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
0             P0                 2            0            1              1   
1             P1                 0            1            0              1   
2             P2                 0            0            1              1   
3             P3                 2            1            0              0   
4             P4                 3            1            1              1   
...          ...               ...          ...          ...            ...   
24995     P24995                 2            1            1              0   
24996     P24996                 0            0            1              1   
24997     P24997                 2            1            1              0   
24998     P24998                 3            0            1              0   
24999     P24999                 3            0            0              1   

       Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
0                 1                0                1              0   
1                 1                0                0              1   
2                 0                0                0              1   
3                 0                1                1              1   
4                 0                0                1              1   
...             ...              ...              ...            ...   
24995             1                1                0              0   
24996             0                1                1              1   
24997             0                1                1              0   
24998             1                1                1              0   
24999             0                0                1              1   

       Sexually Transmitted Infection  MonkeyPox  
0                                   0          0  
1                                   0          1  
2                                   0          1  
3                                   0          1  
4                                   0          1  
...                               ...        ...  
24995                               1          1  
24996                               1          1  
24997                               0          1  
24998                               0          0  
24999                               0          1  

[25000 rows x 11 columns]

In [12]:
x=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values

In [13]:
x

array([[2, 0, 1, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [2, 1, 1, ..., 1, 0, 0],
       [3, 0, 1, ..., 1, 0, 0],
       [3, 0, 0, ..., 1, 1, 0]])

In [14]:
from imblearn.over_sampling import RandomOverSampler
r=RandomOverSampler()
x_data,y_data=r.fit_resample(x,y)

In [15]:
from collections import Counter

In [16]:
print(Counter(y_data))

Counter({0: 15909, 1: 15909})


In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.3,random_state=30)

In [41]:
from sklearn.linear_model import LogisticRegression
l1=LogisticRegression(random_state=20)
l1.fit(x_train,y_train)
y_pred=l1.predict(x_test)
y_pred

array([0, 0, 0, ..., 1, 1, 0])

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac=accuracy_score(y_test,y_pred)*100
ac

60.96794468887492

In [22]:
from sklearn.model_selection import KFold

In [23]:
kf=KFold(n_splits=5,random_state=11,shuffle=True)
kf.get_n_splits(x)
print(kf)

KFold(n_splits=5, random_state=11, shuffle=True)


In [24]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

In [42]:
c_score=cross_val_score(l1,x_train,y_train,cv=kf)
c_score
c=cross_val_predict(l1,x_test,y_test)
c

array([0, 0, 0, ..., 1, 1, 0])

In [27]:
ac1=accuracy_score(y_test,c)*100
ac1

61.240310077519375

In [43]:
from sklearn.ensemble import BaggingClassifier
bg=BaggingClassifier(n_estimators=5,base_estimator=l1,random_state=20)
bg

BaggingClassifier(base_estimator=LogisticRegression(random_state=20),
                  n_estimators=5, random_state=20)

In [29]:
bg.fit(x_train,y_train)

BaggingClassifier(base_estimator=LogisticRegression(), n_estimators=5)

In [30]:
Bg_pred=bg.predict(x_test)
Bg_pred

array([0, 0, 0, ..., 1, 1, 0])

In [31]:
ac_bg=accuracy_score(y_test,Bg_pred)*100
ac_bg

61.00984705635868

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
k_pred=knn.predict(x_test)
k_pred

array([0, 0, 1, ..., 0, 1, 0])

In [34]:
k_ac=accuracy_score(y_test,k_pred)*100
k_ac

60.4965430546826

In [35]:
from sklearn.svm import SVC

In [36]:
s=SVC()

In [37]:
s.fit(x_train,y_train)

SVC()

In [38]:
s_pred=s.predict(x_test)

In [39]:
s_pred

array([0, 0, 1, ..., 0, 1, 0])

In [40]:
s_ac=accuracy_score(y_test,s_pred)*100
s_ac

63.41923318667505